---
  ## Instalaci贸n de Spectrum 10.3 en Linux Red Hat 8/CentOS 8
  ## Autor: Jorge Zavala Navarro
  ## Upload via OwnCloud:
  ## curl -X PUT -u admin:Jorge.Zavala$1974 "https://gnld.dist.werosoft.com.mx/recursos/remote.php/webdav/Documents/ticket1.xml" -F f=@"ticket1.xml"
  ## curl -X PUT -u admin:Jorge.Zavala$1974 "https://gnld.dist.werosoft.com.mx/recursos/remote.php/webdav/Proyectos/Ansible/Downloads/Instalables/Spectrum/InstallSpectrum_v10.3.tar" -F f=@"InstallSpectrum_v10.3.tar" --silent --progress-bar
- name: INSTALAR SPECTRUM 10_3 EN LINUX RED HAT 8.0/CENTOS 8_0 - modif004
  hosts: all

  vars:
          repo_tag: spestrum_10_3

          vars:
          path_media_install_src: /root/Spectrum/Install_Spectrum_10_3_linux/
          path_media_install_dest: /home/Spectrum/Install_Spectrum_10_3_linux/
          path_media_install_dir: /home/Spectrum
          path_media_file_installer: /home/Spectrum/InstallerSpectrum10.3.tar
          path_media_file_src: /home/Spectrum/src/InstallerSpectrum10.3.tar

  tasks:
          - name: Validar si existe la carpeta con la media de instalaci贸n para spectrum
            stat:
                  path: '{{ path_media_install_dest }}'
            register: existe_path_media_install_dest

          - name: Borrar la actual carpeta de la media de instalaci贸n en caso de existir
            file:
                  path: '{{ path_media_install_dest }}'
                  state: absent
            when: existe_path_media_install_dest.stat.exists
           
          - name: Validar si existe la carpeta '{{ path_media_install_dir }}'
            stat:
                  path: '{{ path_media_install_dir }}'
            register: existe_path_media_install_dir


          - name: Crear carpeta '{{ path_media_install_dir }}' para depositar la carpeta del instalable
            file:
                  path: '{{ path_media_install_dir }}'
                  state: directory
                  mode: '0755'
            when: existe_path_media_install_dir.stat.exists == False

          - name: Descargar la media de instalaci贸n desde el portal correspondiente en caso de que aplique
            get_url:
                    url: http://gnld.dist.werosoft.com.mx/recursos/index.php/s/tH5JYRpfIaVoVEf/download
                    dest: '{{ path_media_file_installer }}'
            when: '"DESCARGAR DESDE LA NUVE" in modo_get_installer'

          - name: Copiar el archivo instalador localmente (ya debe de existir) segun las rutas especificadas
            copy:
                  src: '{{ path_media_file_src }}'
                  dest: '{{ path_media_file_installer }}'
                  remote_src: yes
                  owner: root
                  backup: no
            when: '"COPIA LOCAL" in modo_get_installer'

          - name: Descomprimir el instalable y colocamos los archivos en: '{{ path_media_install_dest }}'
            unarchive:
                    src: '{{ path_media_file_installer }}'
                    dest: '{{ path_media_install_dest }}'
                    remote_src: yes

            

          



