yum install libnuma
yum install elfutils-libelf
yum -y install libaio
yum -y install ncurses
yum -y install ncurses-libs
yum -y install xterm
yum -y install ksh
yum -y install xorg-x11-fonts-misc
yum -y install PackageKit-gtk-module
yum -y install libcanberra-gtk2
yum -y install gtk2-engines
yum -y install openmotif
yum -y install glibc
yum -y install nss-softokn-freebl
yum -y install libICE
yum -y install libSM
yum -y install libX11
yum -y install libXext
yum -y install libXft
yum -y install libXmu
yum -y install libXp
yum -y install libXrender
yum -y install libXt
yum -y install fontconfig
yum -y install freetype
yum -y install libjpeg
yum -y install libjpeg-turbo
yum -y install libpng
yum -y install libuuid
yum -y install libxcb
yum -y install libXau
yum -y install expat
yum -y install zlib
yum -y install libstdc++
yum -y install libgcc
yum -y install libXi
yum -y install libXtst
yum -y install perl-LWP-Protocol-https
yum -y install sssd-client.i686

