---
  ## Instalación de Spectrum 10.3 en Linux Red Hat 8/CentOS 8
  ## Autor: Jorge Zavala Navarro
  ## Upload via OwnCloud:
  ## curl -X PUT -u admin:Jorge.Zavala$1974 "https://gnld.dist.werosoft.com.mx/recursos/remote.php/webdav/Documents/ticket1.xml" -F f=@"ticket1.xml"
  ## curl -X PUT -u admin:Jorge.Zavala$1974 "https://gnld.dist.werosoft.com.mx/recursos/remote.php/webdav/Proyectos/Ansible/Downloads/Instalables/Spectrum/InstallSpectrum_v10.3.tar" -F f=@"InstallSpectrum_v10.3.tar" --silent --progress-bar
  ## Variable: path_media_install_dest_form --> Ruta de la media de instalación en caso de no venir vacia
  ## Variable: modo_get_installer --> Modo en como se obtiene el instalador en formato tar
- name: INSTALAR SPECTRUM 10_3 EN LINUX RED HAT 8.0/CENTOS 8_0 - modif004
  hosts: all

  vars:
          repo_tag: spestrum_10_3

          vars:
          path_media_install_src: /root/Spectrum/Install_Spectrum_10_3_linux/
          path_media_install_dest: /home/Spectrum/Install_Spectrum_10_3_linux/
          path_media_install_dir: /home/Spectrum
          path_media_file_installer: /home/Spectrum/InstallerSpectrum10.3.tar
          path_media_file_src: /home/Spectrum/src/InstallerSpectrum10.3.tar
          path_sradmin: /sw/SPECTRUM/SRAdmin
          ruta_carpeta_repogit: /home/ZabbixBDDBackup
          ruta_archivo_repogit: /home/ZabbixBDDBackupGit.zip


  tasks:
          - name: Validar si existe la carpeta con la media de instalación para spectrum
            stat:
                  path: '{{ path_media_install_dest }}'
            register: existe_path_media_install_dest

          - name: Borrar la actual carpeta de la media de instalación en caso de existir
            file:
                  path: '{{ path_media_install_dest }}'
                  state: absent
            when: existe_path_media_install_dest.stat.exists
           
          - name: Validar si existe la carpeta '{{ path_media_install_dir }}'
            stat:
                  path: '{{ path_media_install_dest }}'
            register: existe_path_media_install_dir


          - name: Crear carpeta '{{ path_media_install_dest }}' para depositar la carpeta del instalable
            file:
                  path: '{{ path_media_install_dest }}'
                  state: directory
                  mode: '0755'
            when: existe_path_media_install_dir.stat.exists == False

          - name: Descargar la media de instalación desde el portal correspondiente en caso de que aplique
            get_url:
                    url: http://gnld.dist.werosoft.com.mx/recursos/index.php/s/tH5JYRpfIaVoVEf/download
                    dest: '{{ path_media_file_installer }}'
            when: '"DESCARGAR DESDE LA NUVE" in modo_get_installer'

          - name: Copiar el instalable desde una ruta local (Servidor Destino) ya especificada
            copy:
                  src: '{{ path_media_install_dest_form }}'
                  dest: '{{ path_media_file_installer }}'
                  remote_src: yes
                  owner: root
                  backup: no
            when: '"COPIA LOCAL MANUAL" in modo_get_installer'


          - name: Copiar el archivo instalador localmente (ya debe de existir) segun las rutas especificadas
            copy:
                  src: '{{ path_media_file_src }}'
                  dest: '{{ path_media_file_installer }}'
                  remote_src: yes
                  owner: root
                  backup: no
            when: '"COPIA LOCAL DEFAULT" in modo_get_installer'

          - name: Descomprimir el instalable y colocamos los archivos
            unarchive:
                  src: '{{ path_media_file_installer }}'
                  dest: '{{ path_media_install_dest }}'
                  remote_src: yes


          #########################################################################
          ##
          ## DESCARGAR LOS RECURSOS DEL GIT
          ##
          #########################################################################
          - name: Validar si ya se encuentra instalado el git validando el servicio
            service_facts:
          - debug:
                  msg: Docker installed!
            when: "'git' in services"

          - name: Instalar la aplicación git para poder recuperar los recursos correspondientes
            dnf:
                    name: git
                    state: present
                    ## when: not "'git' in services"

          - name: Validar si existe la carpeta con la información del proyecto contenido en el git
            stat:
                    path: '{{ ruta_carpeta_repogit }}'
            register: existe_ruta_carpeta_repogit

          - name: Eliminar la carpeta con el contenido del proyecto en el git
            file:
                    path: '{{ ruta_carpeta_repogit }}'
                    state: absent
            when: existe_ruta_carpeta_repogit.stat.exists


          - name: Descargar los recursos del git para este proyecto
            git:
                    repo: https://github.com/jzavala74mz/ATower.InstallSpectrumv10.3
                    dest: '{{ ruta_carpeta_repogit }}'
                    archive: '{{ ruta_archivo_repogit }}'



          


          #########################################################################
          ## 
          ## INSTALACIÓN DEL SRAdmin daemond
          ##
          ########################################################################

          - name: Validar si existe la carpeta en donde vamos a colocar el SRAdmin
            stat:
                  path: '{{ path_sradmin }}'
            register: existe_path_sradmin

          - name: Si la carpeta ya existe detenemos la instalación en lo que se deinen nuevas rutas
            meta: end_play
            when: existe_path_sradmin.stat.exists == True

          - name: Crear carpeta '{{ path_sradmin }}' en caso de no existir para depositar la carpeta del instalable
            file:
                  path: '{{ path_sradmin }}'
                  state: directory
                  mode: '0755'
            when: existe_path_sradmin.stat.exists == False

          - name: Copiar el archivo SRadmin.exe de la carpeta de instalaciòn del '{{ path_sradmin }}'
            copy:
                  src: '{{ path_media_install_dest }}sdic/linux/sradmin.exe'
                  dest: '{{ path_sradmin }}/sradmin.exe'
                  remote_src: yes
                  owner: root
                  backup: no

          - name: Copiar el archivo sradmin.rc2 al directorio init.d
            copy:
                  src: '{{ path_media_install_dest }}sdic/linux/sradmin.rc2'
                  dest: '/etc/init.d/sradmin'
                  remote_src: yes
                  owner: root
                  backup: no

          - name: Cambiar los permisos al archivo sradmin 
            file: dest=/etc/init.d/sradmin mode=500


          - name: Ejecutamos el comando /sbin/chkconfig --add sradmin
            command: /sbin/chkconfig --add sradmin

          - name: Iniciar el daemon SRAdmin de spectrum
            command: /etc/init.d/sradmin start 


          - name: ejecutar prueba de archivo de credenciales
            command: '{{ path_media_install_dest }}sdic/sdiclinux.exe -h {{ ruta_archivo_repogit }}/SpectrumHII.hii -p {{ ruta_archivo_repogit }}/FilePassword.rsc -test'


            

          



